use_frameworks!

target 'iOSRunTime_Example' do
  pod 'iOSRunTime', :path => '../'

  target 'iOSRunTime_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
